# Generated by Django 2.2.4 on 2019-08-28 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Plant name', max_length=512, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Plant',
                'verbose_name_plural': 'Plants',
            },
        ),
        migrations.CreateModel(
            name='Datapoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('energy_expected', models.DecimalField(decimal_places=14, max_digits=17)),
                ('energy_observed', models.DecimalField(decimal_places=14, max_digits=17)),
                ('irradiation_expected', models.DecimalField(decimal_places=14, max_digits=17)),
                ('irradiation_observed', models.DecimalField(decimal_places=14, max_digits=17)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_datapoints', to='core.Plant', verbose_name='Plant')),
            ],
        ),
    ]
