# Generated by Django 2.2.4 on 2019-08-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datapoint',
            options={'verbose_name': 'Datapoint', 'verbose_name_plural': 'Datapoints'},
        ),
        migrations.AddField(
            model_name='datapoint',
            name='datetime',
            field=models.DateTimeField(blank=True, help_text='Datapoint extraction datetime', null=True, verbose_name='Datetime'),
        ),
        migrations.AlterUniqueTogether(
            name='datapoint',
            unique_together={('plant', 'datetime')},
        ),
    ]
